version: '3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - consumer
      - producer1
      - producer2
    networks:
      - lab2
    ports:
     - "8080:80"

  producer1:
    build:
      context: ./producer1
      no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2

  producer2:
    build:
      context: ./producer2
      no_cache: true
    env_file:
      - ./MSize.env
    networks:
      - lab2

  consumer:
    build:
      context: ./consumer
      no_cache: true
    networks:
      - lab2
    deploy:
#      replicas: 2 #горизонтальное масштабирование - увеличение кол-ва экземпляров
      resources:
        limits:
          cpus: "4"


networks:
  lab2:
    driver: bridge
